version: "3.9"

services:
  api:
    image: aspnetcore-base-project
    build:
      context: .
      dockerfile: src/application/Dockerfile
    ports:
      - "24470:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: local
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 2gb
    volumes:
      - ./log:/var/log
    links:
      - redis
    
  redis:
    image: redis
    