version: "3.9"

services:
  api:
    image: aspnetcore-base-project
    build:
      context: .
      dockerfile: ./src/application/Dockerfile
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Local
      ASPNETCORE_URLS: "http://*:5000"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 2gb
    volumes:
      - ./log:/var/log
    