version: "3.9"

services:
  db:
    image: mysql:8.0.29-oracle
    container_name: aspnetcore-base-project-mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD-mysql1234}"
    volumes:
      - "${MYSQL_VOLUMES-~/Docker/aspnetcore-base-project/mysql/data}:/var/lib/mysql"